# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/api_def.proto

require 'google/protobuf'

require 'tensorflow/core/framework/attr_value_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/api_def.proto", :syntax => :proto3) do
    add_message "tensorflow.ApiDef" do
      optional :graph_op_name, :string, 1
      optional :deprecation_message, :string, 12
      optional :deprecation_version, :int32, 13
      optional :visibility, :enum, 2, "tensorflow.ApiDef.Visibility"
      repeated :endpoint, :message, 3, "tensorflow.ApiDef.Endpoint"
      repeated :in_arg, :message, 4, "tensorflow.ApiDef.Arg"
      repeated :out_arg, :message, 5, "tensorflow.ApiDef.Arg"
      repeated :arg_order, :string, 11
      repeated :attr, :message, 6, "tensorflow.ApiDef.Attr"
      optional :summary, :string, 7
      optional :description, :string, 8
      optional :description_prefix, :string, 9
      optional :description_suffix, :string, 10
    end
    add_message "tensorflow.ApiDef.Endpoint" do
      optional :name, :string, 1
      optional :deprecated, :bool, 3
      optional :deprecation_version, :int32, 4
    end
    add_message "tensorflow.ApiDef.Arg" do
      optional :name, :string, 1
      optional :rename_to, :string, 2
      optional :description, :string, 3
    end
    add_message "tensorflow.ApiDef.Attr" do
      optional :name, :string, 1
      optional :rename_to, :string, 2
      optional :default_value, :message, 3, "tensorflow.AttrValue"
      optional :description, :string, 4
    end
    add_enum "tensorflow.ApiDef.Visibility" do
      value :DEFAULT_VISIBILITY, 0
      value :VISIBLE, 1
      value :SKIP, 2
      value :HIDDEN, 3
    end
    add_message "tensorflow.ApiDefs" do
      repeated :op, :message, 1, "tensorflow.ApiDef"
    end
  end
end

module Tensorflow
  ApiDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ApiDef").msgclass
  ApiDef::Endpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ApiDef.Endpoint").msgclass
  ApiDef::Arg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ApiDef.Arg").msgclass
  ApiDef::Attr = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ApiDef.Attr").msgclass
  ApiDef::Visibility = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ApiDef.Visibility").enummodule
  ApiDefs = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ApiDefs").msgclass
end
