# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/cost_graph.proto

require 'google/protobuf'

require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/cost_graph.proto", :syntax => :proto3) do
    add_message "tensorflow.CostGraphDef" do
      repeated :node, :message, 1, "tensorflow.CostGraphDef.Node"
    end
    add_message "tensorflow.CostGraphDef.Node" do
      optional :name, :string, 1
      optional :device, :string, 2
      optional :id, :int32, 3
      repeated :input_info, :message, 4, "tensorflow.CostGraphDef.Node.InputInfo"
      repeated :output_info, :message, 5, "tensorflow.CostGraphDef.Node.OutputInfo"
      optional :temporary_memory_size, :int64, 6
      optional :persistent_memory_size, :int64, 12
      optional :host_temp_memory_size, :int64, 10
      optional :device_temp_memory_size, :int64, 11
      optional :device_persistent_memory_size, :int64, 16
      optional :compute_cost, :int64, 9
      optional :compute_time, :int64, 14
      optional :memory_time, :int64, 15
      optional :is_final, :bool, 7
      repeated :control_input, :int32, 8
      optional :inaccurate, :bool, 17
    end
    add_message "tensorflow.CostGraphDef.Node.InputInfo" do
      optional :preceding_node, :int32, 1
      optional :preceding_port, :int32, 2
    end
    add_message "tensorflow.CostGraphDef.Node.OutputInfo" do
      optional :size, :int64, 1
      optional :alias_input_port, :int64, 2
      optional :shape, :message, 3, "tensorflow.TensorShapeProto"
      optional :dtype, :enum, 4, "tensorflow.DataType"
    end
  end
end

module Tensorflow
  CostGraphDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef").msgclass
  CostGraphDef::Node = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef.Node").msgclass
  CostGraphDef::Node::InputInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef.Node.InputInfo").msgclass
  CostGraphDef::Node::OutputInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef.Node.OutputInfo").msgclass
end
