# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/device_attributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/device_attributes.proto", :syntax => :proto3) do
    add_message "tensorflow.InterconnectLink" do
      optional :device_id, :int32, 1
      optional :type, :string, 2
      optional :strength, :int32, 3
    end
    add_message "tensorflow.LocalLinks" do
      repeated :link, :message, 1, "tensorflow.InterconnectLink"
    end
    add_message "tensorflow.DeviceLocality" do
      optional :bus_id, :int32, 1
      optional :numa_node, :int32, 2
      optional :links, :message, 3, "tensorflow.LocalLinks"
    end
    add_message "tensorflow.DeviceAttributes" do
      optional :name, :string, 1
      optional :device_type, :string, 2
      optional :memory_limit, :int64, 4
      optional :locality, :message, 5, "tensorflow.DeviceLocality"
      optional :incarnation, :fixed64, 6
      optional :physical_device_desc, :string, 7
    end
  end
end

module Tensorflow
  InterconnectLink = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.InterconnectLink").msgclass
  LocalLinks = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.LocalLinks").msgclass
  DeviceLocality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeviceLocality").msgclass
  DeviceAttributes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeviceAttributes").msgclass
end
