# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/function.proto

require 'google/protobuf'

require 'tensorflow/core/framework/attr_value_pb'
require 'tensorflow/core/framework/node_def_pb'
require 'tensorflow/core/framework/op_def_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/function.proto", :syntax => :proto3) do
    add_message "tensorflow.FunctionDefLibrary" do
      repeated :function, :message, 1, "tensorflow.FunctionDef"
      repeated :gradient, :message, 2, "tensorflow.GradientDef"
    end
    add_message "tensorflow.FunctionDef" do
      optional :signature, :message, 1, "tensorflow.OpDef"
      map :attr, :string, :message, 5, "tensorflow.AttrValue"
      map :arg_attr, :uint32, :message, 7, "tensorflow.FunctionDef.ArgAttrs"
      repeated :node_def, :message, 3, "tensorflow.NodeDef"
      map :ret, :string, :string, 4
      map :control_ret, :string, :string, 6
    end
    add_message "tensorflow.FunctionDef.ArgAttrs" do
      map :attr, :string, :message, 1, "tensorflow.AttrValue"
    end
    add_message "tensorflow.GradientDef" do
      optional :function_name, :string, 1
      optional :gradient_func, :string, 2
    end
  end
end

module Tensorflow
  FunctionDefLibrary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.FunctionDefLibrary").msgclass
  FunctionDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.FunctionDef").msgclass
  FunctionDef::ArgAttrs = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.FunctionDef.ArgAttrs").msgclass
  GradientDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GradientDef").msgclass
end
