# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/graph_transfer_info.proto

require 'google/protobuf'

require 'tensorflow/core/framework/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/graph_transfer_info.proto", :syntax => :proto3) do
    add_message "tensorflow.GraphTransferNodeInput" do
      optional :node_id, :int32, 1
      optional :output_port, :int32, 2
    end
    add_message "tensorflow.GraphTransferNodeInfo" do
      optional :name, :string, 1
      optional :node_id, :int32, 2
      optional :type_name, :string, 3
      optional :soc_op_id, :int32, 4
      optional :padding_id, :int32, 5
      optional :input_count, :int32, 6
      optional :output_count, :int32, 7
    end
    add_message "tensorflow.GraphTransferConstNodeInfo" do
      optional :name, :string, 1
      optional :node_id, :int32, 2
      repeated :shape, :int64, 3
      optional :data, :bytes, 4
      optional :dtype, :enum, 5, "tensorflow.DataType"
    end
    add_message "tensorflow.GraphTransferNodeInputInfo" do
      optional :node_id, :int32, 1
      repeated :node_input, :message, 2, "tensorflow.GraphTransferNodeInput"
    end
    add_message "tensorflow.GraphTransferNodeOutputInfo" do
      optional :node_id, :int32, 1
      repeated :max_byte_size, :int32, 2
    end
    add_message "tensorflow.GraphTransferGraphInputNodeInfo" do
      optional :name, :string, 1
      repeated :shape, :int64, 2
      optional :dtype, :enum, 3, "tensorflow.DataType"
    end
    add_message "tensorflow.GraphTransferGraphOutputNodeInfo" do
      optional :name, :string, 1
      repeated :shape, :int64, 2
      optional :dtype, :enum, 3, "tensorflow.DataType"
    end
    add_message "tensorflow.GraphTransferInfo" do
      repeated :node_info, :message, 1, "tensorflow.GraphTransferNodeInfo"
      repeated :const_node_info, :message, 2, "tensorflow.GraphTransferConstNodeInfo"
      repeated :node_input_info, :message, 3, "tensorflow.GraphTransferNodeInputInfo"
      repeated :node_output_info, :message, 4, "tensorflow.GraphTransferNodeOutputInfo"
      repeated :graph_input_node_info, :message, 5, "tensorflow.GraphTransferGraphInputNodeInfo"
      repeated :graph_output_node_info, :message, 6, "tensorflow.GraphTransferGraphOutputNodeInfo"
      optional :destination, :enum, 7, "tensorflow.GraphTransferInfo.Destination"
    end
    add_enum "tensorflow.GraphTransferInfo.Destination" do
      value :NOP, 0
      value :HEXAGON, 1
    end
  end
end

module Tensorflow
  GraphTransferNodeInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferNodeInput").msgclass
  GraphTransferNodeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferNodeInfo").msgclass
  GraphTransferConstNodeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferConstNodeInfo").msgclass
  GraphTransferNodeInputInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferNodeInputInfo").msgclass
  GraphTransferNodeOutputInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferNodeOutputInfo").msgclass
  GraphTransferGraphInputNodeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferGraphInputNodeInfo").msgclass
  GraphTransferGraphOutputNodeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferGraphOutputNodeInfo").msgclass
  GraphTransferInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferInfo").msgclass
  GraphTransferInfo::Destination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphTransferInfo.Destination").enummodule
end
