# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/remote_fused_graph_execute_info.proto

require 'google/protobuf'

require 'tensorflow/core/framework/graph_pb'
require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/remote_fused_graph_execute_info.proto", :syntax => :proto3) do
    add_message "tensorflow.RemoteFusedGraphExecuteInfo" do
      optional :remote_graph, :message, 1, "tensorflow.GraphDef"
      repeated :graph_input_node_name, :string, 2
      repeated :graph_output_node_name, :string, 3
      optional :executor_name, :string, 4
      optional :serialized_executor_parameters, :bytes, 5
      repeated :default_graph_input_tensor_shape, :message, 6, "tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto"
      repeated :default_graph_output_tensor_shape, :message, 7, "tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto"
    end
    add_message "tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto" do
      optional :dtype, :enum, 1, "tensorflow.DataType"
      optional :shape, :message, 2, "tensorflow.TensorShapeProto"
    end
  end
end

module Tensorflow
  RemoteFusedGraphExecuteInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RemoteFusedGraphExecuteInfo").msgclass
  RemoteFusedGraphExecuteInfo::TensorShapeTypeProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto").msgclass
end
