# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/step_stats.proto

require 'google/protobuf'

require 'tensorflow/core/framework/allocation_description_pb'
require 'tensorflow/core/framework/tensor_description_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/step_stats.proto", :syntax => :proto3) do
    add_message "tensorflow.AllocationRecord" do
      optional :alloc_micros, :int64, 1
      optional :alloc_bytes, :int64, 2
    end
    add_message "tensorflow.AllocatorMemoryUsed" do
      optional :allocator_name, :string, 1
      optional :total_bytes, :int64, 2
      optional :peak_bytes, :int64, 3
      optional :live_bytes, :int64, 4
      repeated :allocation_records, :message, 6, "tensorflow.AllocationRecord"
      optional :allocator_bytes_in_use, :int64, 5
    end
    add_message "tensorflow.NodeOutput" do
      optional :slot, :int32, 1
      optional :tensor_description, :message, 3, "tensorflow.TensorDescription"
    end
    add_message "tensorflow.MemoryStats" do
      optional :temp_memory_size, :int64, 1
      optional :persistent_memory_size, :int64, 3
      repeated :persistent_tensor_alloc_ids, :int64, 5
      optional :device_temp_memory_size, :int64, 2
      optional :device_persistent_memory_size, :int64, 4
      repeated :device_persistent_tensor_alloc_ids, :int64, 6
    end
    add_message "tensorflow.NodeExecStats" do
      optional :node_name, :string, 1
      optional :all_start_micros, :int64, 2
      optional :op_start_rel_micros, :int64, 3
      optional :op_end_rel_micros, :int64, 4
      optional :all_end_rel_micros, :int64, 5
      repeated :memory, :message, 6, "tensorflow.AllocatorMemoryUsed"
      repeated :output, :message, 7, "tensorflow.NodeOutput"
      optional :timeline_label, :string, 8
      optional :scheduled_micros, :int64, 9
      optional :thread_id, :uint32, 10
      repeated :referenced_tensor, :message, 11, "tensorflow.AllocationDescription"
      optional :memory_stats, :message, 12, "tensorflow.MemoryStats"
      optional :all_start_nanos, :int64, 13
      optional :op_start_rel_nanos, :int64, 14
      optional :op_end_rel_nanos, :int64, 15
      optional :all_end_rel_nanos, :int64, 16
      optional :scheduled_nanos, :int64, 17
    end
    add_message "tensorflow.DeviceStepStats" do
      optional :device, :string, 1
      repeated :node_stats, :message, 2, "tensorflow.NodeExecStats"
      map :thread_names, :uint32, :string, 3
    end
    add_message "tensorflow.StepStats" do
      repeated :dev_stats, :message, 1, "tensorflow.DeviceStepStats"
    end
  end
end

module Tensorflow
  AllocationRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AllocationRecord").msgclass
  AllocatorMemoryUsed = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AllocatorMemoryUsed").msgclass
  NodeOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NodeOutput").msgclass
  MemoryStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemoryStats").msgclass
  NodeExecStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NodeExecStats").msgclass
  DeviceStepStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeviceStepStats").msgclass
  StepStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.StepStats").msgclass
end
