# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/variable.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/framework/variable.proto", :syntax => :proto3) do
    add_message "tensorflow.VariableDef" do
      optional :variable_name, :string, 1
      optional :initial_value_name, :string, 6
      optional :initializer_name, :string, 2
      optional :snapshot_name, :string, 3
      optional :save_slice_info_def, :message, 4, "tensorflow.SaveSliceInfoDef"
      optional :is_resource, :bool, 5
      optional :trainable, :bool, 7
      optional :synchronization, :enum, 8, "tensorflow.VariableSynchronization"
      optional :aggregation, :enum, 9, "tensorflow.VariableAggregation"
    end
    add_message "tensorflow.SaveSliceInfoDef" do
      optional :full_name, :string, 1
      repeated :full_shape, :int64, 2
      repeated :var_offset, :int64, 3
      repeated :var_shape, :int64, 4
    end
    add_enum "tensorflow.VariableSynchronization" do
      value :VARIABLE_SYNCHRONIZATION_AUTO, 0
      value :VARIABLE_SYNCHRONIZATION_NONE, 1
      value :VARIABLE_SYNCHRONIZATION_ON_WRITE, 2
      value :VARIABLE_SYNCHRONIZATION_ON_READ, 3
    end
    add_enum "tensorflow.VariableAggregation" do
      value :VARIABLE_AGGREGATION_NONE, 0
      value :VARIABLE_AGGREGATION_SUM, 1
      value :VARIABLE_AGGREGATION_MEAN, 2
      value :VARIABLE_AGGREGATION_ONLY_FIRST_REPLICA, 3
    end
  end
end

module Tensorflow
  VariableDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.VariableDef").msgclass
  SaveSliceInfoDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SaveSliceInfoDef").msgclass
  VariableSynchronization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.VariableSynchronization").enummodule
  VariableAggregation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.VariableAggregation").enummodule
end
