# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/autotuning.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/duration_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/autotuning.proto", :syntax => :proto3) do
    add_message "tensorflow.CudnnVersion" do
      optional :major, :int32, 1
      optional :minor, :int32, 2
      optional :patch, :int32, 3
    end
    add_message "tensorflow.ComputeCapability" do
      optional :major, :int32, 1
      optional :minor, :int32, 2
    end
    add_message "tensorflow.AutotuneResult" do
      optional :scratch_bytes, :int64, 8
      optional :run_time, :message, 9, "google.protobuf.Duration"
      optional :failure, :message, 7, "tensorflow.AutotuneResult.FailureResult"
      oneof :key do
        optional :conv, :message, 5, "tensorflow.AutotuneResult.ConvKey"
        optional :gemm, :message, 6, "tensorflow.AutotuneResult.GemmKey"
      end
    end
    add_message "tensorflow.AutotuneResult.FailureResult" do
      optional :kind, :enum, 1, "tensorflow.AutotuneResult.FailureKind"
      optional :msg, :string, 2
      optional :buffer_address, :int64, 13
      oneof :key do
        optional :reference_conv, :message, 11, "tensorflow.AutotuneResult.ConvKey"
        optional :reference_gemm, :message, 12, "tensorflow.AutotuneResult.GemmKey"
      end
    end
    add_message "tensorflow.AutotuneResult.ConvKey" do
      optional :algorithm, :int64, 1
      optional :tensor_ops_enabled, :bool, 2
    end
    add_message "tensorflow.AutotuneResult.GemmKey" do
      optional :algorithm, :int64, 1
    end
    add_enum "tensorflow.AutotuneResult.FailureKind" do
      value :UNKNOWN, 0
      value :REDZONE_MODIFIED, 1
      value :WRONG_RESULT, 2
    end
    add_message "tensorflow.AutotuningLog" do
      optional :instr, :message, 1, "google.protobuf.Any"
      repeated :results, :message, 2, "tensorflow.AutotuneResult"
      optional :cudnn_version, :message, 3, "tensorflow.CudnnVersion"
      optional :compute_capability, :message, 4, "tensorflow.ComputeCapability"
      optional :device_pci_bus_id, :string, 5
    end
  end
end

module Tensorflow
  CudnnVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CudnnVersion").msgclass
  ComputeCapability = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ComputeCapability").msgclass
  AutotuneResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AutotuneResult").msgclass
  AutotuneResult::FailureResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AutotuneResult.FailureResult").msgclass
  AutotuneResult::ConvKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AutotuneResult.ConvKey").msgclass
  AutotuneResult::GemmKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AutotuneResult.GemmKey").msgclass
  AutotuneResult::FailureKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AutotuneResult.FailureKind").enummodule
  AutotuningLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AutotuningLog").msgclass
end
