# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/cluster.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/cluster.proto", :syntax => :proto3) do
    add_message "tensorflow.JobDef" do
      optional :name, :string, 1
      map :tasks, :int32, :string, 2
    end
    add_message "tensorflow.ClusterDef" do
      repeated :job, :message, 1, "tensorflow.JobDef"
    end
  end
end

module Tensorflow
  JobDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.JobDef").msgclass
  ClusterDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ClusterDef").msgclass
end
