# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/control_flow.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/control_flow.proto", :syntax => :proto3) do
    add_message "tensorflow.ValuesDef" do
      repeated :values, :string, 1
      map :external_values, :string, :string, 2
    end
    add_message "tensorflow.ControlFlowContextDef" do
      oneof :ctxt do
        optional :cond_ctxt, :message, 1, "tensorflow.CondContextDef"
        optional :while_ctxt, :message, 2, "tensorflow.WhileContextDef"
      end
    end
    add_message "tensorflow.CondContextDef" do
      optional :context_name, :string, 1
      optional :pred_name, :string, 2
      optional :pivot_name, :string, 3
      optional :branch, :int32, 4
      optional :values_def, :message, 5, "tensorflow.ValuesDef"
      repeated :nested_contexts, :message, 6, "tensorflow.ControlFlowContextDef"
    end
    add_message "tensorflow.WhileContextDef" do
      optional :context_name, :string, 1
      optional :parallel_iterations, :int32, 2
      optional :back_prop, :bool, 3
      optional :swap_memory, :bool, 4
      optional :pivot_name, :string, 5
      optional :pivot_for_pred_name, :string, 6
      optional :pivot_for_body_name, :string, 7
      repeated :loop_exit_names, :string, 8
      repeated :loop_enter_names, :string, 10
      optional :values_def, :message, 9, "tensorflow.ValuesDef"
      optional :maximum_iterations_name, :string, 11
      repeated :nested_contexts, :message, 12, "tensorflow.ControlFlowContextDef"
    end
  end
end

module Tensorflow
  ValuesDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ValuesDef").msgclass
  ControlFlowContextDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ControlFlowContextDef").msgclass
  CondContextDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CondContextDef").msgclass
  WhileContextDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.WhileContextDef").msgclass
end
