# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/conv_autotuning.proto

require 'google/protobuf'

require 'tensorflow/stream_executor/dnn_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/conv_autotuning.proto", :syntax => :proto3) do
    add_message "tensorflow.ConvolutionProto" do
      optional :kind, :enum, 1, "stream_executor.dnn.ConvolutionKind"
      optional :input, :message, 2, "stream_executor.dnn.TensorDescriptorProto"
      optional :filter, :message, 3, "stream_executor.dnn.TensorDescriptorProto"
      optional :output, :message, 4, "stream_executor.dnn.TensorDescriptorProto"
      optional :conv_desc, :message, 5, "stream_executor.dnn.ConvolutionDescriptorProto"
      optional :conv_scale, :double, 6
      optional :side_value_scale, :double, 7
      optional :activation, :enum, 8, "stream_executor.dnn.ActivationMode"
      optional :input_address, :int64, 9
      optional :filter_address, :int64, 10
      optional :output_address, :int64, 11
      optional :bias_address, :int64, 12
      optional :side_input_address, :int64, 13
    end
  end
end

module Tensorflow
  ConvolutionProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ConvolutionProto").msgclass
end
