# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/critical_section.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/critical_section.proto", :syntax => :proto3) do
    add_message "tensorflow.CriticalSectionDef" do
      optional :critical_section_name, :string, 1
    end
    add_message "tensorflow.CriticalSectionExecutionDef" do
      optional :execute_in_critical_section_name, :string, 1
      optional :exclusive_resource_access, :bool, 2
    end
  end
end

module Tensorflow
  CriticalSectionDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CriticalSectionDef").msgclass
  CriticalSectionExecutionDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CriticalSectionExecutionDef").msgclass
end
