# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/debug.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/debug.proto", :syntax => :proto3) do
    add_message "tensorflow.DebugTensorWatch" do
      optional :node_name, :string, 1
      optional :output_slot, :int32, 2
      repeated :debug_ops, :string, 3
      repeated :debug_urls, :string, 4
      optional :tolerate_debug_op_creation_failures, :bool, 5
    end
    add_message "tensorflow.DebugOptions" do
      repeated :debug_tensor_watch_opts, :message, 4, "tensorflow.DebugTensorWatch"
      optional :global_step, :int64, 10
      optional :reset_disk_byte_usage, :bool, 11
    end
    add_message "tensorflow.DebuggedSourceFile" do
      optional :host, :string, 1
      optional :file_path, :string, 2
      optional :last_modified, :int64, 3
      optional :bytes, :int64, 4
      repeated :lines, :string, 5
    end
    add_message "tensorflow.DebuggedSourceFiles" do
      repeated :source_files, :message, 1, "tensorflow.DebuggedSourceFile"
    end
  end
end

module Tensorflow
  DebugTensorWatch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DebugTensorWatch").msgclass
  DebugOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DebugOptions").msgclass
  DebuggedSourceFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DebuggedSourceFile").msgclass
  DebuggedSourceFiles = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DebuggedSourceFiles").msgclass
end
