# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/eager_service.proto

require 'google/protobuf'

require 'tensorflow/core/framework/attr_value_pb'
require 'tensorflow/core/framework/device_attributes_pb'
require 'tensorflow/core/framework/function_pb'
require 'tensorflow/core/framework/tensor_pb'
require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/types_pb'
require 'tensorflow/core/framework/versions_pb'
require 'tensorflow/core/protobuf/tensorflow_server_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/eager_service.proto", :syntax => :proto3) do
    add_message "tensorflow.eager.RemoteTensorHandle" do
      optional :op_id, :int64, 1
      optional :output_num, :int32, 2
      optional :device, :string, 3
      optional :op_device, :string, 4
      optional :dtype, :enum, 5, "tensorflow.DataType"
    end
    add_message "tensorflow.eager.Operation" do
      optional :id, :int64, 1
      optional :name, :string, 2
      repeated :inputs, :message, 3, "tensorflow.eager.RemoteTensorHandle"
      repeated :control_op_ids, :int64, 4
      map :attrs, :string, :message, 5, "tensorflow.AttrValue"
      optional :device, :string, 6
    end
    add_message "tensorflow.eager.QueueItem" do
      oneof :item do
        optional :handle_to_decref, :message, 1, "tensorflow.eager.RemoteTensorHandle"
        optional :operation, :message, 2, "tensorflow.eager.Operation"
      end
    end
    add_message "tensorflow.eager.QueueResponse" do
      repeated :shape, :message, 1, "tensorflow.TensorShapeProto"
    end
    add_message "tensorflow.eager.CreateContextRequest" do
      optional :server_def, :message, 1, "tensorflow.ServerDef"
      optional :async, :bool, 2
      optional :keep_alive_secs, :int64, 3
      optional :version_def, :message, 4, "tensorflow.VersionDef"
      repeated :cluster_device_attributes, :message, 6, "tensorflow.DeviceAttributes"
      optional :context_id, :fixed64, 7
    end
    add_message "tensorflow.eager.CreateContextResponse" do
      repeated :device_attributes, :message, 2, "tensorflow.DeviceAttributes"
    end
    add_message "tensorflow.eager.EnqueueRequest" do
      optional :context_id, :fixed64, 1
      repeated :queue, :message, 3, "tensorflow.eager.QueueItem"
    end
    add_message "tensorflow.eager.EnqueueResponse" do
      repeated :queue_response, :message, 1, "tensorflow.eager.QueueResponse"
    end
    add_message "tensorflow.eager.WaitQueueDoneRequest" do
      optional :context_id, :fixed64, 1
      repeated :op_id, :int64, 2
    end
    add_message "tensorflow.eager.WaitQueueDoneResponse" do
    end
    add_message "tensorflow.eager.KeepAliveRequest" do
      optional :context_id, :fixed64, 1
    end
    add_message "tensorflow.eager.KeepAliveResponse" do
    end
    add_message "tensorflow.eager.CloseContextRequest" do
      optional :context_id, :fixed64, 1
    end
    add_message "tensorflow.eager.CloseContextResponse" do
    end
    add_message "tensorflow.eager.RegisterFunctionRequest" do
      optional :context_id, :fixed64, 1
      optional :function_def, :message, 2, "tensorflow.FunctionDef"
    end
    add_message "tensorflow.eager.RegisterFunctionResponse" do
    end
    add_message "tensorflow.eager.SendTensorRequest" do
      optional :context_id, :fixed64, 1
      optional :op_id, :int64, 2
      repeated :tensors, :message, 3, "tensorflow.TensorProto"
      optional :device_name, :string, 4
    end
    add_message "tensorflow.eager.SendTensorResponse" do
    end
  end
end

module Tensorflow
  module Eager
    RemoteTensorHandle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.RemoteTensorHandle").msgclass
    Operation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.Operation").msgclass
    QueueItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.QueueItem").msgclass
    QueueResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.QueueResponse").msgclass
    CreateContextRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.CreateContextRequest").msgclass
    CreateContextResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.CreateContextResponse").msgclass
    EnqueueRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.EnqueueRequest").msgclass
    EnqueueResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.EnqueueResponse").msgclass
    WaitQueueDoneRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.WaitQueueDoneRequest").msgclass
    WaitQueueDoneResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.WaitQueueDoneResponse").msgclass
    KeepAliveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.KeepAliveRequest").msgclass
    KeepAliveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.KeepAliveResponse").msgclass
    CloseContextRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.CloseContextRequest").msgclass
    CloseContextResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.CloseContextResponse").msgclass
    RegisterFunctionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.RegisterFunctionRequest").msgclass
    RegisterFunctionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.RegisterFunctionResponse").msgclass
    SendTensorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.SendTensorRequest").msgclass
    SendTensorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.eager.SendTensorResponse").msgclass
  end
end
