# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/graph_debug_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/graph_debug_info.proto", :syntax => :proto3) do
    add_message "tensorflow.GraphDebugInfo" do
      repeated :files, :string, 1
      map :traces, :string, :message, 2, "tensorflow.GraphDebugInfo.StackTrace"
    end
    add_message "tensorflow.GraphDebugInfo.FileLineCol" do
      optional :file_index, :int32, 1
      optional :line, :int32, 2
      optional :col, :int32, 3
      optional :func, :string, 4
      optional :code, :string, 5
    end
    add_message "tensorflow.GraphDebugInfo.StackTrace" do
      repeated :file_line_cols, :message, 1, "tensorflow.GraphDebugInfo.FileLineCol"
    end
  end
end

module Tensorflow
  GraphDebugInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphDebugInfo").msgclass
  GraphDebugInfo::FileLineCol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphDebugInfo.FileLineCol").msgclass
  GraphDebugInfo::StackTrace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphDebugInfo.StackTrace").msgclass
end
