# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/master_service.proto

require 'google/protobuf'

require 'tensorflow/core/protobuf/master_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/master_service.proto", :syntax => :proto3) do
  end
end

module Tensorflow
  module Grpc
  end
end
