# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/master.proto

require 'google/protobuf'

require 'tensorflow/core/framework/device_attributes_pb'
require 'tensorflow/core/framework/graph_pb'
require 'tensorflow/core/framework/tensor_pb'
require 'tensorflow/core/lib/core/error_codes_pb'
require 'tensorflow/core/protobuf/config_pb'
require 'tensorflow/core/protobuf/named_tensor_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/master.proto", :syntax => :proto3) do
    add_message "tensorflow.CreateSessionRequest" do
      optional :graph_def, :message, 1, "tensorflow.GraphDef"
      optional :config, :message, 2, "tensorflow.ConfigProto"
      optional :target, :string, 3
    end
    add_message "tensorflow.CreateSessionResponse" do
      optional :session_handle, :string, 1
      optional :graph_version, :int64, 2
    end
    add_message "tensorflow.ExtendSessionRequest" do
      optional :session_handle, :string, 1
      optional :graph_def, :message, 2, "tensorflow.GraphDef"
      optional :current_graph_version, :int64, 3
    end
    add_message "tensorflow.ExtendSessionResponse" do
      optional :new_graph_version, :int64, 4
    end
    add_message "tensorflow.RunStepRequest" do
      optional :session_handle, :string, 1
      repeated :feed, :message, 2, "tensorflow.NamedTensorProto"
      repeated :fetch, :string, 3
      repeated :target, :string, 4
      optional :options, :message, 5, "tensorflow.RunOptions"
      optional :partial_run_handle, :string, 6
      optional :store_errors_in_response_body, :bool, 7
      optional :request_id, :int64, 8
    end
    add_message "tensorflow.RunStepResponse" do
      repeated :tensor, :message, 1, "tensorflow.NamedTensorProto"
      optional :metadata, :message, 2, "tensorflow.RunMetadata"
      optional :status_code, :enum, 3, "tensorflow.error.Code"
      optional :status_error_message, :string, 4
    end
    add_message "tensorflow.PartialRunSetupRequest" do
      optional :session_handle, :string, 1
      repeated :feed, :string, 2
      repeated :fetch, :string, 3
      repeated :target, :string, 4
      optional :request_id, :int64, 5
    end
    add_message "tensorflow.PartialRunSetupResponse" do
      optional :partial_run_handle, :string, 1
    end
    add_message "tensorflow.CloseSessionRequest" do
      optional :session_handle, :string, 1
    end
    add_message "tensorflow.CloseSessionResponse" do
    end
    add_message "tensorflow.ResetRequest" do
      repeated :container, :string, 1
      repeated :device_filters, :string, 2
    end
    add_message "tensorflow.ResetResponse" do
    end
    add_message "tensorflow.ListDevicesRequest" do
      optional :session_handle, :string, 1
    end
    add_message "tensorflow.ListDevicesResponse" do
      repeated :local_device, :message, 1, "tensorflow.DeviceAttributes"
      repeated :remote_device, :message, 2, "tensorflow.DeviceAttributes"
    end
    add_message "tensorflow.MakeCallableRequest" do
      optional :session_handle, :string, 1
      optional :options, :message, 2, "tensorflow.CallableOptions"
      optional :request_id, :int64, 3
    end
    add_message "tensorflow.MakeCallableResponse" do
      optional :handle, :int64, 1
    end
    add_message "tensorflow.RunCallableRequest" do
      optional :session_handle, :string, 1
      optional :handle, :int64, 2
      repeated :feed, :message, 3, "tensorflow.TensorProto"
      optional :request_id, :int64, 4
    end
    add_message "tensorflow.RunCallableResponse" do
      repeated :fetch, :message, 1, "tensorflow.TensorProto"
      optional :metadata, :message, 2, "tensorflow.RunMetadata"
    end
    add_message "tensorflow.ReleaseCallableRequest" do
      optional :session_handle, :string, 1
      optional :handle, :int64, 2
    end
    add_message "tensorflow.ReleaseCallableResponse" do
    end
  end
end

module Tensorflow
  CreateSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CreateSessionRequest").msgclass
  CreateSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CreateSessionResponse").msgclass
  ExtendSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ExtendSessionRequest").msgclass
  ExtendSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ExtendSessionResponse").msgclass
  RunStepRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunStepRequest").msgclass
  RunStepResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunStepResponse").msgclass
  PartialRunSetupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.PartialRunSetupRequest").msgclass
  PartialRunSetupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.PartialRunSetupResponse").msgclass
  CloseSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CloseSessionRequest").msgclass
  CloseSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CloseSessionResponse").msgclass
  ResetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ResetRequest").msgclass
  ResetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ResetResponse").msgclass
  ListDevicesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ListDevicesRequest").msgclass
  ListDevicesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ListDevicesResponse").msgclass
  MakeCallableRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MakeCallableRequest").msgclass
  MakeCallableResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MakeCallableResponse").msgclass
  RunCallableRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunCallableRequest").msgclass
  RunCallableResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunCallableResponse").msgclass
  ReleaseCallableRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ReleaseCallableRequest").msgclass
  ReleaseCallableResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ReleaseCallableResponse").msgclass
end
