# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/meta_graph.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'tensorflow/core/framework/graph_pb'
require 'tensorflow/core/framework/op_def_pb'
require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/types_pb'
require 'tensorflow/core/protobuf/saved_object_graph_pb'
require 'tensorflow/core/protobuf/saver_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/meta_graph.proto", :syntax => :proto3) do
    add_message "tensorflow.MetaGraphDef" do
      optional :meta_info_def, :message, 1, "tensorflow.MetaGraphDef.MetaInfoDef"
      optional :graph_def, :message, 2, "tensorflow.GraphDef"
      optional :saver_def, :message, 3, "tensorflow.SaverDef"
      map :collection_def, :string, :message, 4, "tensorflow.CollectionDef"
      map :signature_def, :string, :message, 5, "tensorflow.SignatureDef"
      repeated :asset_file_def, :message, 6, "tensorflow.AssetFileDef"
      optional :object_graph_def, :message, 7, "tensorflow.SavedObjectGraph"
    end
    add_message "tensorflow.MetaGraphDef.MetaInfoDef" do
      optional :meta_graph_version, :string, 1
      optional :stripped_op_list, :message, 2, "tensorflow.OpList"
      optional :any_info, :message, 3, "google.protobuf.Any"
      repeated :tags, :string, 4
      optional :tensorflow_version, :string, 5
      optional :tensorflow_git_version, :string, 6
      optional :stripped_default_attrs, :bool, 7
    end
    add_message "tensorflow.CollectionDef" do
      oneof :kind do
        optional :node_list, :message, 1, "tensorflow.CollectionDef.NodeList"
        optional :bytes_list, :message, 2, "tensorflow.CollectionDef.BytesList"
        optional :int64_list, :message, 3, "tensorflow.CollectionDef.Int64List"
        optional :float_list, :message, 4, "tensorflow.CollectionDef.FloatList"
        optional :any_list, :message, 5, "tensorflow.CollectionDef.AnyList"
      end
    end
    add_message "tensorflow.CollectionDef.NodeList" do
      repeated :value, :string, 1
    end
    add_message "tensorflow.CollectionDef.BytesList" do
      repeated :value, :bytes, 1
    end
    add_message "tensorflow.CollectionDef.Int64List" do
      repeated :value, :int64, 1
    end
    add_message "tensorflow.CollectionDef.FloatList" do
      repeated :value, :float, 1
    end
    add_message "tensorflow.CollectionDef.AnyList" do
      repeated :value, :message, 1, "google.protobuf.Any"
    end
    add_message "tensorflow.TensorInfo" do
      optional :dtype, :enum, 2, "tensorflow.DataType"
      optional :tensor_shape, :message, 3, "tensorflow.TensorShapeProto"
      oneof :encoding do
        optional :name, :string, 1
        optional :coo_sparse, :message, 4, "tensorflow.TensorInfo.CooSparse"
      end
    end
    add_message "tensorflow.TensorInfo.CooSparse" do
      optional :values_tensor_name, :string, 1
      optional :indices_tensor_name, :string, 2
      optional :dense_shape_tensor_name, :string, 3
    end
    add_message "tensorflow.SignatureDef" do
      map :inputs, :string, :message, 1, "tensorflow.TensorInfo"
      map :outputs, :string, :message, 2, "tensorflow.TensorInfo"
      optional :method_name, :string, 3
    end
    add_message "tensorflow.AssetFileDef" do
      optional :tensor_info, :message, 1, "tensorflow.TensorInfo"
      optional :filename, :string, 2
    end
  end
end

module Tensorflow
  MetaGraphDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MetaGraphDef").msgclass
  MetaGraphDef::MetaInfoDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MetaGraphDef.MetaInfoDef").msgclass
  CollectionDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CollectionDef").msgclass
  CollectionDef::NodeList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CollectionDef.NodeList").msgclass
  CollectionDef::BytesList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CollectionDef.BytesList").msgclass
  CollectionDef::Int64List = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CollectionDef.Int64List").msgclass
  CollectionDef::FloatList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CollectionDef.FloatList").msgclass
  CollectionDef::AnyList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CollectionDef.AnyList").msgclass
  TensorInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorInfo").msgclass
  TensorInfo::CooSparse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorInfo.CooSparse").msgclass
  SignatureDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SignatureDef").msgclass
  AssetFileDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AssetFileDef").msgclass
end
