# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/named_tensor.proto

require 'google/protobuf'

require 'tensorflow/core/framework/tensor_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/named_tensor.proto", :syntax => :proto3) do
    add_message "tensorflow.NamedTensorProto" do
      optional :name, :string, 1
      optional :tensor, :message, 2, "tensorflow.TensorProto"
    end
  end
end

module Tensorflow
  NamedTensorProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NamedTensorProto").msgclass
end
