# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/queue_runner.proto

require 'google/protobuf'

require 'tensorflow/core/lib/core/error_codes_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/queue_runner.proto", :syntax => :proto3) do
    add_message "tensorflow.QueueRunnerDef" do
      optional :queue_name, :string, 1
      repeated :enqueue_op_name, :string, 2
      optional :close_op_name, :string, 3
      optional :cancel_op_name, :string, 4
      repeated :queue_closed_exception_types, :enum, 5, "tensorflow.error.Code"
    end
  end
end

module Tensorflow
  QueueRunnerDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.QueueRunnerDef").msgclass
end
