# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/replay_log.proto

require 'google/protobuf'

require 'tensorflow/core/protobuf/master_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/replay_log.proto", :syntax => :proto3) do
    add_message "tensorflow.NewReplaySession" do
      optional :devices, :message, 1, "tensorflow.ListDevicesResponse"
      optional :session_handle, :string, 2
    end
    add_message "tensorflow.ReplayOp" do
      optional :start_time_us, :double, 31
      optional :end_time_us, :double, 32
      oneof :op do
        optional :create_session, :message, 1, "tensorflow.CreateSessionRequest"
        optional :extend_session, :message, 2, "tensorflow.ExtendSessionRequest"
        optional :partial_run_setup, :message, 3, "tensorflow.PartialRunSetupRequest"
        optional :run_step, :message, 4, "tensorflow.RunStepRequest"
        optional :close_session, :message, 5, "tensorflow.CloseSessionRequest"
        optional :list_devices, :message, 6, "tensorflow.ListDevicesRequest"
        optional :reset_request, :message, 7, "tensorflow.ResetRequest"
        optional :make_callable, :message, 8, "tensorflow.MakeCallableRequest"
        optional :run_callable, :message, 9, "tensorflow.RunCallableRequest"
        optional :release_callable, :message, 10, "tensorflow.ReleaseCallableRequest"
        optional :new_replay_session, :message, 11, "tensorflow.NewReplaySession"
      end
      oneof :response do
        optional :create_session_response, :message, 21, "tensorflow.CreateSessionResponse"
        optional :extend_session_response, :message, 22, "tensorflow.ExtendSessionResponse"
        optional :partial_run_setup_response, :message, 23, "tensorflow.PartialRunSetupResponse"
        optional :run_step_response, :message, 24, "tensorflow.RunStepResponse"
        optional :close_session_response, :message, 25, "tensorflow.CloseSessionResponse"
        optional :list_devices_response, :message, 26, "tensorflow.ListDevicesResponse"
        optional :reset_request_response, :message, 27, "tensorflow.ResetResponse"
        optional :make_callable_response, :message, 28, "tensorflow.MakeCallableResponse"
        optional :run_callable_response, :message, 29, "tensorflow.RunCallableResponse"
        optional :release_callable_response, :message, 30, "tensorflow.ReleaseCallableResponse"
      end
    end
  end
end

module Tensorflow
  NewReplaySession = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NewReplaySession").msgclass
  ReplayOp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ReplayOp").msgclass
end
