# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/rewriter_config.proto

require 'google/protobuf'

require 'tensorflow/core/framework/attr_value_pb'
require 'tensorflow/core/protobuf/verifier_config_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/rewriter_config.proto", :syntax => :proto3) do
    add_message "tensorflow.AutoParallelOptions" do
      optional :enable, :bool, 1
      optional :num_replicas, :int32, 2
    end
    add_message "tensorflow.ScopedAllocatorOptions" do
      repeated :enable_op, :string, 1
    end
    add_message "tensorflow.RewriterConfig" do
      optional :layout_optimizer, :enum, 1, "tensorflow.RewriterConfig.Toggle"
      optional :constant_folding, :enum, 3, "tensorflow.RewriterConfig.Toggle"
      optional :shape_optimization, :enum, 13, "tensorflow.RewriterConfig.Toggle"
      optional :remapping, :enum, 14, "tensorflow.RewriterConfig.Toggle"
      optional :arithmetic_optimization, :enum, 7, "tensorflow.RewriterConfig.Toggle"
      optional :dependency_optimization, :enum, 8, "tensorflow.RewriterConfig.Toggle"
      optional :loop_optimization, :enum, 9, "tensorflow.RewriterConfig.Toggle"
      optional :function_optimization, :enum, 10, "tensorflow.RewriterConfig.Toggle"
      optional :debug_stripper, :enum, 11, "tensorflow.RewriterConfig.Toggle"
      optional :disable_model_pruning, :bool, 2
      optional :scoped_allocator_optimization, :enum, 15, "tensorflow.RewriterConfig.Toggle"
      optional :pin_to_host_optimization, :enum, 18, "tensorflow.RewriterConfig.Toggle"
      optional :implementation_selector, :enum, 22, "tensorflow.RewriterConfig.Toggle"
      optional :auto_mixed_precision, :enum, 23, "tensorflow.RewriterConfig.Toggle"
      optional :disable_meta_optimizer, :bool, 19
      optional :meta_optimizer_iterations, :enum, 12, "tensorflow.RewriterConfig.NumIterationsType"
      optional :min_graph_nodes, :int32, 17
      optional :memory_optimization, :enum, 4, "tensorflow.RewriterConfig.MemOptType"
      optional :memory_optimizer_target_node_name_scope, :string, 6
      optional :meta_optimizer_timeout_ms, :int64, 20
      optional :auto_parallel, :message, 5, "tensorflow.AutoParallelOptions"
      optional :fail_on_optimizer_errors, :bool, 21
      optional :scoped_allocator_opts, :message, 16, "tensorflow.ScopedAllocatorOptions"
      repeated :optimizers, :string, 100
      repeated :custom_optimizers, :message, 200, "tensorflow.RewriterConfig.CustomGraphOptimizer"
      optional :inter_optimizer_verifier_config, :message, 300, "tensorflow.VerifierConfig"
      optional :post_optimization_verifier_config, :message, 301, "tensorflow.VerifierConfig"
    end
    add_message "tensorflow.RewriterConfig.CustomGraphOptimizer" do
      optional :name, :string, 1
      map :parameter_map, :string, :message, 2, "tensorflow.AttrValue"
    end
    add_enum "tensorflow.RewriterConfig.Toggle" do
      value :DEFAULT, 0
      value :ON, 1
      value :OFF, 2
      value :AGGRESSIVE, 3
    end
    add_enum "tensorflow.RewriterConfig.NumIterationsType" do
      value :DEFAULT_NUM_ITERS, 0
      value :ONE, 1
      value :TWO, 2
    end
    add_enum "tensorflow.RewriterConfig.MemOptType" do
      value :DEFAULT_MEM_OPT, 0
      value :NO_MEM_OPT, 1
      value :MANUAL, 2
      value :SWAPPING_HEURISTICS, 4
      value :RECOMPUTATION_HEURISTICS, 5
      value :SCHEDULING_HEURISTICS, 6
      value :HEURISTICS, 3
    end
  end
end

module Tensorflow
  AutoParallelOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AutoParallelOptions").msgclass
  ScopedAllocatorOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ScopedAllocatorOptions").msgclass
  RewriterConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RewriterConfig").msgclass
  RewriterConfig::CustomGraphOptimizer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RewriterConfig.CustomGraphOptimizer").msgclass
  RewriterConfig::Toggle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RewriterConfig.Toggle").enummodule
  RewriterConfig::NumIterationsType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RewriterConfig.NumIterationsType").enummodule
  RewriterConfig::MemOptType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RewriterConfig.MemOptType").enummodule
end
