# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/saved_model.proto

require 'google/protobuf'

require 'tensorflow/core/protobuf/meta_graph_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/saved_model.proto", :syntax => :proto3) do
    add_message "tensorflow.SavedModel" do
      optional :saved_model_schema_version, :int64, 1
      repeated :meta_graphs, :message, 2, "tensorflow.MetaGraphDef"
    end
  end
end

module Tensorflow
  SavedModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedModel").msgclass
end
