# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/saved_object_graph.proto

require 'google/protobuf'

require 'tensorflow/core/protobuf/trackable_object_graph_pb'
require 'tensorflow/core/protobuf/struct_pb'
require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/types_pb'
require 'tensorflow/core/framework/versions_pb'
require 'tensorflow/core/framework/variable_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/saved_object_graph.proto", :syntax => :proto3) do
    add_message "tensorflow.SavedObjectGraph" do
      repeated :nodes, :message, 1, "tensorflow.SavedObject"
      map :concrete_functions, :string, :message, 2, "tensorflow.SavedConcreteFunction"
    end
    add_message "tensorflow.SavedObject" do
      repeated :children, :message, 1, "tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference"
      repeated :slot_variables, :message, 3, "tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference"
      oneof :kind do
        optional :user_object, :message, 4, "tensorflow.SavedUserObject"
        optional :asset, :message, 5, "tensorflow.SavedAsset"
        optional :function, :message, 6, "tensorflow.SavedFunction"
        optional :variable, :message, 7, "tensorflow.SavedVariable"
        optional :bare_concrete_function, :message, 8, "tensorflow.SavedBareConcreteFunction"
        optional :constant, :message, 9, "tensorflow.SavedConstant"
        optional :resource, :message, 10, "tensorflow.SavedResource"
      end
    end
    add_message "tensorflow.SavedUserObject" do
      optional :identifier, :string, 1
      optional :version, :message, 2, "tensorflow.VersionDef"
      optional :metadata, :string, 3
    end
    add_message "tensorflow.SavedAsset" do
      optional :asset_file_def_index, :int32, 1
    end
    add_message "tensorflow.SavedFunction" do
      repeated :concrete_functions, :string, 1
      optional :function_spec, :message, 2, "tensorflow.FunctionSpec"
    end
    add_message "tensorflow.SavedConcreteFunction" do
      repeated :bound_inputs, :int32, 2
      optional :canonicalized_input_signature, :message, 3, "tensorflow.StructuredValue"
      optional :output_signature, :message, 4, "tensorflow.StructuredValue"
    end
    add_message "tensorflow.SavedBareConcreteFunction" do
      optional :concrete_function_name, :string, 1
      repeated :argument_keywords, :string, 2
      optional :allowed_positional_arguments, :int64, 3
    end
    add_message "tensorflow.SavedConstant" do
      optional :operation, :string, 1
    end
    add_message "tensorflow.SavedVariable" do
      optional :dtype, :enum, 1, "tensorflow.DataType"
      optional :shape, :message, 2, "tensorflow.TensorShapeProto"
      optional :trainable, :bool, 3
      optional :synchronization, :enum, 4, "tensorflow.VariableSynchronization"
      optional :aggregation, :enum, 5, "tensorflow.VariableAggregation"
      optional :name, :string, 6
    end
    add_message "tensorflow.FunctionSpec" do
      optional :fullargspec, :message, 1, "tensorflow.StructuredValue"
      optional :is_method, :bool, 2
      optional :input_signature, :message, 5, "tensorflow.StructuredValue"
    end
    add_message "tensorflow.SavedResource" do
      optional :device, :string, 1
    end
  end
end

module Tensorflow
  SavedObjectGraph = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedObjectGraph").msgclass
  SavedObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedObject").msgclass
  SavedUserObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedUserObject").msgclass
  SavedAsset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedAsset").msgclass
  SavedFunction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedFunction").msgclass
  SavedConcreteFunction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedConcreteFunction").msgclass
  SavedBareConcreteFunction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedBareConcreteFunction").msgclass
  SavedConstant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedConstant").msgclass
  SavedVariable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedVariable").msgclass
  FunctionSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.FunctionSpec").msgclass
  SavedResource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SavedResource").msgclass
end
