# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/saver.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/saver.proto", :syntax => :proto3) do
    add_message "tensorflow.SaverDef" do
      optional :filename_tensor_name, :string, 1
      optional :save_tensor_name, :string, 2
      optional :restore_op_name, :string, 3
      optional :max_to_keep, :int32, 4
      optional :sharded, :bool, 5
      optional :keep_checkpoint_every_n_hours, :float, 6
      optional :version, :enum, 7, "tensorflow.SaverDef.CheckpointFormatVersion"
    end
    add_enum "tensorflow.SaverDef.CheckpointFormatVersion" do
      value :LEGACY, 0
      value :V1, 1
      value :V2, 2
    end
  end
end

module Tensorflow
  SaverDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SaverDef").msgclass
  SaverDef::CheckpointFormatVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SaverDef.CheckpointFormatVersion").enummodule
end
