# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/struct.proto

require 'google/protobuf'

require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/struct.proto", :syntax => :proto3) do
    add_message "tensorflow.StructuredValue" do
      oneof :kind do
        optional :none_value, :message, 1, "tensorflow.NoneValue"
        optional :float64_value, :double, 11
        optional :int64_value, :sint64, 12
        optional :string_value, :string, 13
        optional :bool_value, :bool, 14
        optional :tensor_shape_value, :message, 31, "tensorflow.TensorShapeProto"
        optional :tensor_dtype_value, :enum, 32, "tensorflow.DataType"
        optional :tensor_spec_value, :message, 33, "tensorflow.TensorSpecProto"
        optional :type_spec_value, :message, 34, "tensorflow.TypeSpecProto"
        optional :list_value, :message, 51, "tensorflow.ListValue"
        optional :tuple_value, :message, 52, "tensorflow.TupleValue"
        optional :dict_value, :message, 53, "tensorflow.DictValue"
        optional :named_tuple_value, :message, 54, "tensorflow.NamedTupleValue"
      end
    end
    add_message "tensorflow.NoneValue" do
    end
    add_message "tensorflow.ListValue" do
      repeated :values, :message, 1, "tensorflow.StructuredValue"
    end
    add_message "tensorflow.TupleValue" do
      repeated :values, :message, 1, "tensorflow.StructuredValue"
    end
    add_message "tensorflow.DictValue" do
      map :fields, :string, :message, 1, "tensorflow.StructuredValue"
    end
    add_message "tensorflow.PairValue" do
      optional :key, :string, 1
      optional :value, :message, 2, "tensorflow.StructuredValue"
    end
    add_message "tensorflow.NamedTupleValue" do
      optional :name, :string, 1
      repeated :values, :message, 2, "tensorflow.PairValue"
    end
    add_message "tensorflow.TensorSpecProto" do
      optional :name, :string, 1
      optional :shape, :message, 2, "tensorflow.TensorShapeProto"
      optional :dtype, :enum, 3, "tensorflow.DataType"
    end
    add_message "tensorflow.TypeSpecProto" do
      optional :type_spec_class, :enum, 1, "tensorflow.TypeSpecProto.TypeSpecClass"
      optional :type_state, :message, 2, "tensorflow.StructuredValue"
      optional :type_spec_class_name, :string, 3
    end
    add_enum "tensorflow.TypeSpecProto.TypeSpecClass" do
      value :UNKNOWN, 0
      value :SPARSE_TENSOR_SPEC, 1
      value :INDEXED_SLICES_SPEC, 2
      value :RAGGED_TENSOR_SPEC, 3
      value :TENSOR_ARRAY_SPEC, 4
      value :DATA_DATASET_SPEC, 5
      value :DATA_ITERATOR_SPEC, 6
      value :OPTIONAL_SPEC, 7
      value :PER_REPLICA_SPEC, 8
    end
  end
end

module Tensorflow
  StructuredValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.StructuredValue").msgclass
  NoneValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NoneValue").msgclass
  ListValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ListValue").msgclass
  TupleValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TupleValue").msgclass
  DictValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DictValue").msgclass
  PairValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.PairValue").msgclass
  NamedTupleValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NamedTupleValue").msgclass
  TensorSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorSpecProto").msgclass
  TypeSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TypeSpecProto").msgclass
  TypeSpecProto::TypeSpecClass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TypeSpecProto.TypeSpecClass").enummodule
end
