# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/tensorflow_server.proto

require 'google/protobuf'

require 'tensorflow/core/protobuf/config_pb'
require 'tensorflow/core/protobuf/cluster_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/tensorflow_server.proto", :syntax => :proto3) do
    add_message "tensorflow.ServerDef" do
      optional :cluster, :message, 1, "tensorflow.ClusterDef"
      optional :job_name, :string, 2
      optional :task_index, :int32, 3
      optional :default_session_config, :message, 4, "tensorflow.ConfigProto"
      optional :protocol, :string, 5
    end
  end
end

module Tensorflow
  ServerDef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ServerDef").msgclass
end
