# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/tensor_bundle.proto

require 'google/protobuf'

require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/tensor_slice_pb'
require 'tensorflow/core/framework/types_pb'
require 'tensorflow/core/framework/versions_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/tensor_bundle.proto", :syntax => :proto3) do
    add_message "tensorflow.BundleHeaderProto" do
      optional :num_shards, :int32, 1
      optional :endianness, :enum, 2, "tensorflow.BundleHeaderProto.Endianness"
      optional :version, :message, 3, "tensorflow.VersionDef"
    end
    add_enum "tensorflow.BundleHeaderProto.Endianness" do
      value :LITTLE, 0
      value :BIG, 1
    end
    add_message "tensorflow.BundleEntryProto" do
      optional :dtype, :enum, 1, "tensorflow.DataType"
      optional :shape, :message, 2, "tensorflow.TensorShapeProto"
      optional :shard_id, :int32, 3
      optional :offset, :int64, 4
      optional :size, :int64, 5
      optional :crc32c, :fixed32, 6
      repeated :slices, :message, 7, "tensorflow.TensorSliceProto"
    end
  end
end

module Tensorflow
  BundleHeaderProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.BundleHeaderProto").msgclass
  BundleHeaderProto::Endianness = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.BundleHeaderProto.Endianness").enummodule
  BundleEntryProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.BundleEntryProto").msgclass
end
