# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/transport_options.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/transport_options.proto", :syntax => :proto3) do
    add_message "tensorflow.RecvBufRespExtra" do
      repeated :tensor_content, :bytes, 1
    end
  end
end

module Tensorflow
  RecvBufRespExtra = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RecvBufRespExtra").msgclass
end
