# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/worker.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'tensorflow/core/framework/cost_graph_pb'
require 'tensorflow/core/framework/device_attributes_pb'
require 'tensorflow/core/framework/graph_pb'
require 'tensorflow/core/framework/step_stats_pb'
require 'tensorflow/core/framework/tensor_pb'
require 'tensorflow/core/framework/tensor_shape_pb'
require 'tensorflow/core/framework/types_pb'
require 'tensorflow/core/lib/core/error_codes_pb'
require 'tensorflow/core/protobuf/config_pb'
require 'tensorflow/core/protobuf/debug_pb'
require 'tensorflow/core/protobuf/named_tensor_pb'
require 'tensorflow/core/protobuf/tensorflow_server_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/protobuf/worker.proto", :syntax => :proto3) do
    add_message "tensorflow.GetStatusRequest" do
    end
    add_message "tensorflow.GetStatusResponse" do
      repeated :device_attributes, :message, 1, "tensorflow.DeviceAttributes"
    end
    add_message "tensorflow.CreateWorkerSessionRequest" do
      optional :session_handle, :string, 1
      optional :server_def, :message, 2, "tensorflow.ServerDef"
      optional :isolate_session_state, :bool, 3
      repeated :cluster_device_attributes, :message, 4, "tensorflow.DeviceAttributes"
    end
    add_message "tensorflow.CreateWorkerSessionResponse" do
    end
    add_message "tensorflow.DeleteWorkerSessionRequest" do
      optional :session_handle, :string, 1
    end
    add_message "tensorflow.DeleteWorkerSessionResponse" do
    end
    add_message "tensorflow.RegisterGraphRequest" do
      optional :session_handle, :string, 1
      optional :create_worker_session_called, :bool, 6
      optional :graph_def, :message, 2, "tensorflow.GraphDef"
      optional :has_control_flow, :bool, 3
      optional :graph_options, :message, 4, "tensorflow.GraphOptions"
      optional :debug_options, :message, 5, "tensorflow.DebugOptions"
      optional :collective_graph_key, :int64, 7
    end
    add_message "tensorflow.RegisterGraphResponse" do
      optional :graph_handle, :string, 1
    end
    add_message "tensorflow.DeregisterGraphRequest" do
      optional :session_handle, :string, 2
      optional :create_worker_session_called, :bool, 3
      optional :graph_handle, :string, 1
    end
    add_message "tensorflow.DeregisterGraphResponse" do
    end
    add_message "tensorflow.CleanupAllRequest" do
      repeated :container, :string, 1
    end
    add_message "tensorflow.CleanupAllResponse" do
    end
    add_message "tensorflow.ExecutorOpts" do
      optional :record_costs, :bool, 1
      optional :record_timeline, :bool, 3
      optional :record_partition_graphs, :bool, 4
      optional :report_tensor_allocations_upon_oom, :bool, 5
    end
    add_message "tensorflow.RunGraphRequest" do
      optional :session_handle, :string, 8
      optional :create_worker_session_called, :bool, 10
      optional :graph_handle, :string, 1
      optional :step_id, :int64, 2
      optional :exec_opts, :message, 5, "tensorflow.ExecutorOpts"
      repeated :send, :message, 3, "tensorflow.NamedTensorProto"
      repeated :recv_key, :string, 4
      optional :is_partial, :bool, 6
      optional :is_last_partial_run, :bool, 7
      optional :store_errors_in_response_body, :bool, 9
      optional :request_id, :int64, 11
    end
    add_message "tensorflow.RunGraphResponse" do
      repeated :recv, :message, 1, "tensorflow.NamedTensorProto"
      optional :step_stats, :message, 2, "tensorflow.StepStats"
      optional :cost_graph, :message, 3, "tensorflow.CostGraphDef"
      repeated :partition_graph, :message, 4, "tensorflow.GraphDef"
      optional :status_code, :enum, 5, "tensorflow.error.Code"
      optional :status_error_message, :string, 6
    end
    add_message "tensorflow.CleanupGraphRequest" do
      optional :step_id, :int64, 1
    end
    add_message "tensorflow.CleanupGraphResponse" do
    end
    add_message "tensorflow.RecvTensorRequest" do
      optional :step_id, :int64, 1
      optional :rendezvous_key, :string, 2
      optional :dma_ok, :bool, 3
      optional :client_locality, :message, 4, "tensorflow.DeviceLocality"
      optional :server_locality, :message, 5, "tensorflow.DeviceLocality"
      optional :transport_options, :message, 6, "google.protobuf.Any"
      optional :request_id, :int64, 7
    end
    add_message "tensorflow.RecvTensorResponse" do
      optional :tensor, :message, 1, "tensorflow.TensorProto"
      optional :is_dead, :bool, 2
      optional :send_start_micros, :int64, 3
      optional :transport_options, :message, 4, "google.protobuf.Any"
      optional :require_ack, :bool, 5
    end
    add_message "tensorflow.MarkRecvFinishedRequest" do
      optional :request_id, :int64, 1
    end
    add_message "tensorflow.MarkRecvFinishedResponse" do
    end
    add_message "tensorflow.LoggingRequest" do
      optional :enable_rpc_logging, :bool, 1
      optional :disable_rpc_logging, :bool, 4
      optional :clear, :bool, 2
      repeated :fetch_step_id, :int64, 3
    end
    add_message "tensorflow.LabeledStepStats" do
      optional :step_id, :int64, 1
      optional :step_stats, :message, 2, "tensorflow.StepStats"
    end
    add_message "tensorflow.LoggingResponse" do
      repeated :step, :message, 1, "tensorflow.LabeledStepStats"
    end
    add_message "tensorflow.TraceOpts" do
      optional :duration, :double, 1
      optional :use_step_profiler, :bool, 2
      optional :use_kernel_profiler, :bool, 3
      optional :use_extended_profiler, :bool, 4
      optional :use_gpu_profiler, :bool, 5
      optional :use_sample_profiler, :bool, 6
    end
    add_message "tensorflow.TracingRequest" do
      optional :options, :message, 1, "tensorflow.TraceOpts"
    end
    add_message "tensorflow.TracingResponse" do
    end
    add_message "tensorflow.RecvBufRequest" do
      optional :step_id, :int64, 1
      optional :buf_rendezvous_key, :string, 2
      optional :num_bytes, :int64, 3
      optional :buf_ptr, :fixed64, 4
      optional :client_locality, :message, 5, "tensorflow.DeviceLocality"
      optional :server_locality, :message, 6, "tensorflow.DeviceLocality"
      optional :transport_options, :message, 7, "google.protobuf.Any"
      optional :src_device, :string, 8
      optional :dst_device, :string, 9
      optional :request_id, :int64, 10
      optional :src_incarnation, :uint64, 11
    end
    add_message "tensorflow.RecvBufResponse" do
      optional :buf_ptr, :fixed64, 1
      optional :num_bytes, :int64, 2
      optional :is_dead, :bool, 3
      optional :transport_options, :message, 4, "google.protobuf.Any"
      optional :send_start_micros, :int64, 5
      optional :require_ack, :bool, 6
    end
    add_message "tensorflow.CompleteGroupRequest" do
      optional :group_key, :int32, 1
      optional :group_size, :int32, 2
      optional :device_type, :string, 3
      repeated :device_name, :string, 4
      optional :collective_type, :int32, 5
    end
    add_message "tensorflow.CompleteGroupResponse" do
      optional :group_key, :int32, 1
      optional :group_size, :int32, 2
      optional :device_type, :string, 3
      optional :num_tasks, :int32, 4
      repeated :device_name, :string, 5
      repeated :task_name, :string, 6
      optional :communicator_key, :bytes, 7
    end
    add_message "tensorflow.CompleteInstanceRequest" do
      optional :name, :string, 1
      optional :type, :int32, 2
      optional :data_type, :enum, 3, "tensorflow.DataType"
      optional :shape, :message, 4, "tensorflow.TensorShapeProto"
      optional :group_key, :int32, 5
      optional :group_size, :int32, 6
      optional :instance_key, :int32, 7
      optional :device_type, :string, 8
      repeated :subdiv_offset, :int32, 9
      optional :device, :string, 10
      optional :is_source, :bool, 11
    end
    add_message "tensorflow.CompleteInstanceResponse" do
      optional :instance_key, :int32, 1
      optional :source_rank, :int32, 2
    end
    add_message "tensorflow.GetStepSequenceRequest" do
      repeated :graph_key, :int64, 1
    end
    add_message "tensorflow.StepSequence" do
      optional :graph_key, :int64, 1
      optional :next_step_id, :int64, 2
    end
    add_message "tensorflow.GetStepSequenceResponse" do
      repeated :step_sequence, :message, 1, "tensorflow.StepSequence"
    end
  end
end

module Tensorflow
  GetStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GetStatusRequest").msgclass
  GetStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GetStatusResponse").msgclass
  CreateWorkerSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CreateWorkerSessionRequest").msgclass
  CreateWorkerSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CreateWorkerSessionResponse").msgclass
  DeleteWorkerSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeleteWorkerSessionRequest").msgclass
  DeleteWorkerSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeleteWorkerSessionResponse").msgclass
  RegisterGraphRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RegisterGraphRequest").msgclass
  RegisterGraphResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RegisterGraphResponse").msgclass
  DeregisterGraphRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeregisterGraphRequest").msgclass
  DeregisterGraphResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeregisterGraphResponse").msgclass
  CleanupAllRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CleanupAllRequest").msgclass
  CleanupAllResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CleanupAllResponse").msgclass
  ExecutorOpts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ExecutorOpts").msgclass
  RunGraphRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunGraphRequest").msgclass
  RunGraphResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunGraphResponse").msgclass
  CleanupGraphRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CleanupGraphRequest").msgclass
  CleanupGraphResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CleanupGraphResponse").msgclass
  RecvTensorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RecvTensorRequest").msgclass
  RecvTensorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RecvTensorResponse").msgclass
  MarkRecvFinishedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MarkRecvFinishedRequest").msgclass
  MarkRecvFinishedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MarkRecvFinishedResponse").msgclass
  LoggingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.LoggingRequest").msgclass
  LabeledStepStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.LabeledStepStats").msgclass
  LoggingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.LoggingResponse").msgclass
  TraceOpts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TraceOpts").msgclass
  TracingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TracingRequest").msgclass
  TracingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TracingResponse").msgclass
  RecvBufRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RecvBufRequest").msgclass
  RecvBufResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RecvBufResponse").msgclass
  CompleteGroupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CompleteGroupRequest").msgclass
  CompleteGroupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CompleteGroupResponse").msgclass
  CompleteInstanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CompleteInstanceRequest").msgclass
  CompleteInstanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CompleteInstanceResponse").msgclass
  GetStepSequenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GetStepSequenceRequest").msgclass
  StepSequence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.StepSequence").msgclass
  GetStepSequenceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GetStepSequenceResponse").msgclass
end
