# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/lib/core/error_codes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("core/lib/core/error_codes.proto", :syntax => :proto3) do
    add_enum "tensorflow.error.Code" do
      value :OK, 0
      value :CANCELLED, 1
      value :UNKNOWN, 2
      value :INVALID_ARGUMENT, 3
      value :DEADLINE_EXCEEDED, 4
      value :NOT_FOUND, 5
      value :ALREADY_EXISTS, 6
      value :PERMISSION_DENIED, 7
      value :UNAUTHENTICATED, 16
      value :RESOURCE_EXHAUSTED, 8
      value :FAILED_PRECONDITION, 9
      value :ABORTED, 10
      value :OUT_OF_RANGE, 11
      value :UNIMPLEMENTED, 12
      value :INTERNAL, 13
      value :UNAVAILABLE, 14
      value :DATA_LOSS, 15
      value :DO_NOT_USE_RESERVED_FOR_FUTURE_EXPANSION_USE_DEFAULT_IN_SWITCH_INSTEAD_, 20
    end
  end
end

module Tensorflow
  module Error
    Code = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.error.Code").enummodule
  end
end
